### ISSUE TITLE
추가정보 입력창 개선사항

### ISSUE THREAD

**Issue by jdji** [jdji/pyHasher#3]
**오류에 대하여 기술해주세요**
사용 중 발견한 오류에 대하여 분명하고 간결하게 설명부탁드립니다.
1. Ctrl+C, Ctrl+V 기능 미제공되어 불편함
2. 메모창 작성 후 재 클릭 후 내용이 전부 삭제됨. 메모입력창 아래에 "소스코드/바이러리 등을 입력해주세요"라는 문구가 들어가면 좋을 것 같음
3. 추가정보 입력 은 체크하고, 인수인계증 생성은 체크하지 않는 경우, 인수인계증이 생성됨

**오류를 재현하기 위한 절차**
오류를 재현하기 위한 절차를 단계별로 설명해주세요
1. '...' 메뉴로 간다
2. '....'를 클릭한다.
3. 오류를 확인한다.

**스크린 샷 또는 로그기록**
가능하다면 오류 상황에 대한 화면 또는 로그파일(pyHasher.log)을 첨부해주세요

**운영환경 :**
 - OS: [e.g. 한글 윈도우 또는 영문 윈도구]
 - Version [e.g. 10 또는 10 pro]

**기타**
추가적인 내용을 기술해주세요

**Comment by initZio** [comment]
2번 항목에 대한 캡처파일 보내드립니다.
![PyHasher_메모_개선요청사항](https://user-images.githubusercontent.com/71298289/93190361-3d9f2000-f77e-11ea-972f-9dd22ce0a79e.JPG)

**Comment by jdji** [comment]
버전 0.9.82에서 개선하였습니다.
